"""Контракты API ↔ web, сгенерированные из packages/contracts/schemas (ADR-0005).

Импортировать типы отсюда, а не из `generated` напрямую: при перегенерации меняются
только внутренности `generated`, точка входа остаётся стабильной.
"""

from app.contracts.generated.agent_config_schema import (
    AgentConfig,
    CardAction,
    CatalogConfig,
    ConfirmLabels,
    FormConfig,
    KnowledgeSearchConfig,
    ScenarioConfig,
    SlotDefinition,
)
from app.contracts.generated.components_schema import (
    Action,
    ComparisonTable,
    ComparisonTableRow,
    Component,
    Confirm,
    Form,
    FormField,
    Price,
    ProductCard,
    ProductCarousel,
    SourceItem,
    Sources,
)
from app.contracts.generated.conversations_schema import (
    ComponentBlock,
    CreateConversationRequest,
    CreateConversationResponse,
    HistoryMessage,
    MessageBlock,
    MessageHistory,
    SendMessageRequest,
    TextBlock,
)
from app.contracts.generated.envelope_schema import Envelope
from app.contracts.generated.events_schema import (
    ComponentData,
    ComponentEvent,
    DoneData,
    DoneEvent,
    DoneUsage,
    ErrorData,
    ErrorEvent,
    Event,
    StatusData,
    StatusEvent,
    SuggestionItem,
    SuggestionsData,
    SuggestionsEvent,
    TextDeltaData,
    TextDeltaEvent,
    TextDoneData,
    TextDoneEvent,
    ToolFinishedData,
    ToolFinishedEvent,
    ToolStartedData,
    ToolStartedEvent,
    TurnStartedEvent,
)
from app.contracts.generated.http_error_schema import HttpError, HttpErrorBody
from app.contracts.generated.public_config_schema import PublicAssistant, PublicConfig
from app.contracts.generated.tools_schema import (
    HttpToolDefinition,
    ToolDefinition,
    ToolError,
    ToolResult,
)
from app.contracts.generated.user_input_schema import (
    ActionInput,
    FormSubmitInput,
    TextInput,
    UserInput,
)
from app.contracts.generated.widget_embed_schema import WidgetEmbed

__all__ = [
    "Action",
    "ActionInput",
    "AgentConfig",
    "CardAction",
    "CatalogConfig",
    "ComparisonTable",
    "ComparisonTableRow",
    "Component",
    "ComponentBlock",
    "ComponentData",
    "ComponentEvent",
    "Confirm",
    "ConfirmLabels",
    "CreateConversationRequest",
    "CreateConversationResponse",
    "DoneData",
    "DoneEvent",
    "DoneUsage",
    "Envelope",
    "ErrorData",
    "ErrorEvent",
    "Event",
    "Form",
    "FormConfig",
    "FormField",
    "FormSubmitInput",
    "HistoryMessage",
    "HttpError",
    "HttpErrorBody",
    "HttpToolDefinition",
    "KnowledgeSearchConfig",
    "MessageBlock",
    "MessageHistory",
    "Price",
    "ProductCard",
    "ProductCarousel",
    "PublicAssistant",
    "PublicConfig",
    "ScenarioConfig",
    "SendMessageRequest",
    "SlotDefinition",
    "SourceItem",
    "Sources",
    "StatusData",
    "StatusEvent",
    "SuggestionItem",
    "SuggestionsData",
    "SuggestionsEvent",
    "TextBlock",
    "TextDeltaData",
    "TextDeltaEvent",
    "TextDoneData",
    "TextDoneEvent",
    "TextInput",
    "ToolDefinition",
    "ToolError",
    "ToolFinishedData",
    "ToolFinishedEvent",
    "ToolResult",
    "ToolStartedData",
    "ToolStartedEvent",
    "TurnStartedEvent",
    "UserInput",
    "WidgetEmbed",
]
